name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    name: Check PR's lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest" # Specify the Dagger version to use. It's recommanded to stay in sync with the latest.
          verb: call
          module: github.com/fixentropy-io/daggerverse
          args: on-pull-request --url ${{ github.server_url }}/${{ github.repository }} --branch ${{ github.head_ref }}
