name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publishing the package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # ← nécessaire pour npm Trusted Publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          module: github.com/fixentropy-io/daggerverse
          args: on-publish --source=. --git-url ${{ github.server_url }}/${{ github.repository }}
